version: 2
jobs:
    build:
        docker:
            - image: circleci/php:7.2-node-browsers

        steps:
            - checkout
            -   run:
                    name: "Install dependencies"
                    command: sudo apt update && sudo docker-php-ext-install zip && php -d memory_limit=-1 $(which composer) install
            -   run:
                    name: "Run tests"
                    command: ./vendor/bin/phpunit --coverage-html build/coverage-reports --whitelist src tests
            -   store_artifacts:
                    path: build/coverage-reports